name: build-and-test

on:
  push:
    branches:
      - '**'

jobs:
  bnt:
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [jazzy]
        above: [true]
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware@sha256:ebf8d4b6dc0fefe0e9d2727ec79919b423d8bf384f2b54a051abe248ba3dd624

          - rosdistro: jazzy
            container: ghcr.io/autowarefoundation/autoware:core-common-devel-jazzy-amd64@sha256:733dcaab22e0af103b73acdb63389d4781baf2c731caf859d1c84ec2c6d8816c

    uses: ./.github/workflows/build-and-test-reusable.yaml

    with:
      rosdistro: ${{ matrix.rosdistro }}
      container: ${{ matrix.container }}
      pull-ccache: false
      push-ccache: true
      cache-key-element: build
      above: ${{ matrix.above }}
      codecov-flag: total-${{ matrix.rosdistro }}
      concurrency-group: build-and-test-${{ matrix.rosdistro }}${{ matrix.above && '-above' || '' }}-${{ github.ref }}-${{ github.run_id }}
      runner: ${{ matrix.above && '["self-hosted","Linux","X64"]' || '["ubuntu-latest"]' }}

    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
